# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

### Create an array

In [1]:
import numpy as np ## Shift+Enter

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [4]:
list_of_lists=[1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,23)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22])

In [7]:
np.arange(10,98,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [14]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
np.random.rand(2,4)


array([[5.75545824e-04, 8.12294042e-01, 2.32067081e-03, 3.83490954e-01],
       [5.33054810e-01, 5.24053406e-01, 1.38953625e-01, 7.42431426e-02]])

In [25]:
np.random.randn(2,4)

array([[-0.50719948, -1.01107013,  0.70911985, -0.64351085],
       [ 0.23440606, -0.23686575,  0.63365949,  0.34478606]])

In [51]:
np.random.randint(1,10,10)

array([9, 6, 7, 5, 5, 4, 9, 9, 8, 3])

In [39]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [45]:
rand_array=np.random.randint(0,10,5)
rand_array

array([0, 0, 5, 6, 9])

In [41]:
sample_array.min()

2

In [42]:
sample_array.argmin()

0

In [43]:
rand_array.argmin()

1

In [46]:
rand_array.max()

9

In [47]:
rand_array.argmax()

4

In [48]:
sample_array.argmax()

17

In [52]:
sample_array.dtype

dtype('int32')

In [53]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a=np.random.rand(2,3)
a

array([[0.49339213, 0.36022038, 0.5422599 ],
       [0.97491243, 0.83066055, 0.54075161]])

In [55]:
a.T


array([[0.49339213, 0.97491243],
       [0.36022038, 0.83066055],
       [0.5422599 , 0.54075161]])

In [56]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [58]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [59]:
sample_array=sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [62]:
sample_array[6]=100
sample_array

IndexError: index 6 is out of bounds for axis 0 with size 6

In [63]:
sample_array=np.arange(10,100)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [64]:
sample_array[0:5]

array([10, 11, 12, 13, 14])

In [65]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [66]:
sample_array[1:5]=1001
sample_array

array([  10, 1001, 1001, 1001, 1001,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

In [ ]:
### Recap

In [ ]:
### Code to import Numpy?
### Create an array of 10 zeros with integer datatype
### Create normal distribution of shape 2x 5
### Create unit vector of float data type with shape 3x7
### Identity matrix of 10x10
### O/p:5,10,15,20,25

In [ ]:
import numpy as np

In [ ]:
array=np.zeros(10)
array

In [ ]:
array=np.zeros(10,dtype=int)
print(array)


In [ ]:
np.zeros((6),dtype=int)


In [ ]:
np.random.randn(2,5)


In [ ]:
np.ones((3,7))


In [67]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [68]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
var=[5,10,15,20,25]
np.array(var)


In [ ]:
np.arange(5,30,5)


In [ ]:
np.linspace(5,25,5)


### Two-Dimensional array

In [ ]:
import numpy as np

In [ ]:
sample_matrix=np.array(([24,13,2,15],[15,54,65,23],[56,76,24,7]))
sample_matrix

In [ ]:
sample_matrix[2:,1:3]


In [ ]:
sample_matrix[0][2]

In [ ]:
sample_matrix[1][3]

In [ ]:
sample_matrix[2,:]

In [ ]:
sample_matrix[1:2,2:3]

In [ ]:
sample_matrix[1:,2:]

In [ ]:
sample_matrix[2]

In [ ]:
sample_array=np.arange(1,31)
sample_array

In [ ]:
sample_array+sample_array

In [ ]:
np.exp(sample_array)

In [ ]:
np.sqrt(sample_array)

In [ ]:
np.log(sample_array)

In [ ]:
np.max(sample_array)

In [ ]:
np.min(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.square(sample_array)

In [ ]:
np.std(sample_array)

In [ ]:
np.var(sample_array)


In [ ]:
np.mean(sample_array)

In [ ]:
array=np.random.randn(3,4) ### normal distribution
array

In [ ]:
np.round(array,decimals=3)

In [ ]:
fruits=np.array(['apple','orange','mango','apple','orange'])
np.unique(fruits)

### Pandas

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

### Pandas dataframe and indexing

In [ ]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

In [ ]:
sports1['basketball']


In [ ]:
sports1['golf']

In [ ]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'],)
sports2


In [ ]:
sports1+sports2

In [ ]:

df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

In [ ]:
df1['Score2']

In [ ]:
df1[['Score1','Score2','Score3']]

In [ ]:
df1[['Score4','Score2','Score5']]

In [ ]:
df1['Score6']=df1['Score1']+df1['Score2']
df1


In [ ]:
df1.drop("Score3",axis=1)

In [ ]:
df1.drop('E')

In [ ]:
df1.drop('Score1',axis=1) 


In [ ]:
df1.drop("A",axis=0)


In [ ]:
df1.drop(["Score1","Score2"],axis=1)


In [ ]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

In [ ]:
df.drop('ID',axis=1)

In [ ]:
df.drop(3)

In [ ]:
df[['Name','Profit']]

In [ ]:
df[['Name','ID']]

In [ ]:
df=pd.read_csv("innercity.csv")

In [ ]:
df.head()

In [ ]:
### Assessment

1) Create a null vector of size 10
2) Create a null vector of size 10 but the fifth value should be one
3) Create a vector with values ranging from 10 to 65
4) Reverse the above vector
5) Create a 3x3 matrix with values ranging from 0 to 8


In [ ]:
import numpy as np
np.zeros(10)

In [ ]:
a=np.zeros(10)
a[4]=1
a

In [ ]:
z=np.arange(10,66)
z

In [ ]:
z=np.arange(65,9,-1)
z

In [ ]:
x =  np.arange(0,9).reshape(3,3)
print(x)


In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df=pd.read_csv("Automobile.csv")

In [ ]:
df.head()

In [ ]:
df

In [ ]:
df.tail()

In [ ]:
df.sample()

In [ ]:
df.sample(10)

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.info()

In [ ]:
Roll_no=pd.Series([1,2,3,4,5,6,7,8],index=["Madhu","Dillisree","Philip","Preetham","Rupesh","Sesha","Tanuja","Vasanth"])
                

In [ ]:
Roll_no

In [ ]:
Roll_no["Sesha"]

In [ ]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

In [ ]:
df={'Numbers':[1,2,3,4,5,6,7,8],'Names':["Madhu","Dillisree","Philip","Preetham","Rupesh","Sesha","Tanuja","Vasanth"]}
Roll_no=pd.DataFrame(df)
Roll_no               

In [ ]:
Roll_no.drop(3)

In [ ]:
Roll_no.drop("Numbers",axis=1)